server:
  port: 9000
  servlet:
    #  全局路径配置
    context-path: /river
spring:
  application:
    name: river
  datasource:
    url: jdbc:mysql://localhost:3306/river?serverTimezone=GMT&useSSL=false&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: xp14459048

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.coatardbul.river.model.entity

logging:
  path: logs/
  level:
    com.springboot.cloud: debug
    java.sql.PreparedStatement: debug